// artifacts/portfolio/src/components/Hero.tsx
import { useTyping } from "../hooks/useTyping";

export default function Hero() {
  const typedText = useTyping();

  return (
    <section
      id="hero"
      style={{
        minHeight: "100vh",
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        alignItems: "center",
        padding: "0 6%",
        paddingTop: "80px",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {/* BG */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          zIndex: 0,
          background:
            "radial-gradient(ellipse 80% 80% at 80% 50%, rgba(124,58,237,0.15) 0%, transparent 70%), radial-gradient(ellipse 40% 40% at 20% 80%, rgba(6,182,212,0.08) 0%, transparent 60%)",
        }}
      />

      {/* Content */}
      <div style={{ position: "relative", zIndex: 2 }}>
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "0.5rem",
            fontSize: "0.72rem",
            letterSpacing: "0.15em",
            textTransform: "uppercase",
            color: "#06b6d4",
            border: "1px solid rgba(6,182,212,0.3)",
            padding: "0.4rem 0.9rem",
            borderRadius: "2px",
            marginBottom: "1.8rem",
            animation: "fadeUp 0.6s ease both",
          }}
        >
          <span
            style={{
              width: "6px",
              height: "6px",
              borderRadius: "50%",
              background: "#06b6d4",
              animation: "pulse-dot 1.5s infinite",
            }}
          />
          Open to new opportunities
        </div>

        <h1
          style={{
            fontFamily: "'Syne', sans-serif",
            fontSize: "clamp(2.6rem, 6vw, 5rem)",
            fontWeight: 800,
            lineHeight: 1,
            letterSpacing: "-0.03em",
            animation: "fadeUp 0.7s 0.1s ease both",
          }}
        >
          Hi, I'm Manav
          <span
            style={{
              display: "block",
              background: "linear-gradient(135deg, #06b6d4 0%, #7c3aed 50%, #f472b6 100%)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              minHeight: "1.2em",
            }}
          >
            {typedText}
            <span className="typing-cursor" />
          </span>
        </h1>

        <p
          style={{
            marginTop: "1.5rem",
            color: "#64748b",
            fontSize: "0.88rem",
            lineHeight: 1.9,
            maxWidth: "480px",
            animation: "fadeUp 0.7s 0.2s ease both",
          }}
        >
          Full-Stack Developer with 2.4+ years of experience building scalable
          web applications with Angular, .NET Core, Web API, and SQL — with
          growing expertise in React.js, Python, and AWS cloud infrastructure.
        </p>

        <div
          style={{
            marginTop: "2.5rem",
            display: "flex",
            gap: "1rem",
            flexWrap: "wrap",
            animation: "fadeUp 0.7s 0.3s ease both",
          }}
        >
          <a
            href="#projects"
            style={{
              padding: "0.85rem 2rem",
              background: "#7c3aed",
              color: "#fff",
              borderRadius: "4px",
              fontFamily: "'Space Mono', monospace",
              fontSize: "0.82rem",
              letterSpacing: "0.05em",
              textDecoration: "none",
              transition: "all 0.3s",
              boxShadow: "0 0 30px rgba(124,58,237,0.4)",
              display: "inline-block",
            }}
            onMouseEnter={e => {
              (e.currentTarget as HTMLElement).style.transform = "translateY(-2px)";
              (e.currentTarget as HTMLElement).style.boxShadow = "0 0 50px rgba(124,58,237,0.6)";
            }}
            onMouseLeave={e => {
              (e.currentTarget as HTMLElement).style.transform = "translateY(0)";
              (e.currentTarget as HTMLElement).style.boxShadow = "0 0 30px rgba(124,58,237,0.4)";
            }}
          >
            View My Work
          </a>
          <a
            href="mailto:nandamanav7@gmail.com"
            style={{
              padding: "0.85rem 2rem",
              color: "#e2e8f0",
              border: "1px solid rgba(255,255,255,0.08)",
              borderRadius: "4px",
              fontFamily: "'Space Mono', monospace",
              fontSize: "0.82rem",
              letterSpacing: "0.05em",
              textDecoration: "none",
              transition: "all 0.3s",
              display: "inline-block",
            }}
            onMouseEnter={e => {
              const el = e.currentTarget as HTMLElement;
              el.style.borderColor = "#06b6d4";
              el.style.color = "#06b6d4";
              el.style.transform = "translateY(-2px)";
            }}
            onMouseLeave={e => {
              const el = e.currentTarget as HTMLElement;
              el.style.borderColor = "rgba(255,255,255,0.08)";
              el.style.color = "#e2e8f0";
              el.style.transform = "translateY(0)";
            }}
          >
            Get In Touch
          </a>
        </div>

        {/* Stats */}
        <div
          style={{
            marginTop: "3rem",
            display: "flex",
            gap: "2.5rem",
            animation: "fadeUp 0.7s 0.4s ease both",
          }}
        >
          {[
            { num: "2.4+", label: "Yrs Experience" },
            { num: "9+", label: "Apps Shipped" },
            { num: "9.05", label: "B.Tech CGPA" },
          ].map((s) => (
            <div key={s.label}>
              <div
                style={{
                  fontFamily: "'Syne', sans-serif",
                  fontWeight: 800,
                  fontSize: "2rem",
                  background: "linear-gradient(135deg, #06b6d4, #7c3aed)",
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                }}
              >
                {s.num}
              </div>
              <div
                style={{
                  fontSize: "0.68rem",
                  color: "#64748b",
                  letterSpacing: "0.08em",
                  marginTop: "0.2rem",
                }}
              >
                {s.label}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Photo */}
      <div
        style={{
          position: "relative",
          zIndex: 2,
          display: "flex",
          justifyContent: "flex-end",
          alignItems: "center",
          animation: "fadeIn 1s 0.5s ease both",
        }}
      >
        <div
          style={{
            width: "min(380px, 45vw)",
            aspectRatio: "3/4",
            borderRadius: "8px",
            overflow: "hidden",
            position: "relative",
            border: "1px solid rgba(124,58,237,0.3)",
            boxShadow: "0 0 60px rgba(124,58,237,0.15)",
          }}
        >
          <div
            style={{
              width: "100%",
              height: "100%",
              background: "linear-gradient(160deg, #1a1a3e 0%, #0d0d20 100%)",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              gap: "1rem",
            }}
          >
            <div
              style={{
                fontFamily: "'Syne', sans-serif",
                fontSize: "6rem",
                fontWeight: 800,
                background: "linear-gradient(135deg, #06b6d4, #7c3aed)",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
              }}
            >
              MN
            </div>
            <div
              style={{
                fontSize: "0.75rem",
                letterSpacing: "0.2em",
                color: "#64748b",
                textTransform: "uppercase",
              }}
            >
              Manav Nanda
            </div>
          </div>

          {/* Floating badge 1 */}
          <div
            style={{
              position: "absolute",
              bottom: "-16px",
              left: "-30px",
              background: "#111128",
              border: "1px solid rgba(74,222,128,0.3)",
              padding: "0.8rem 1.2rem",
              borderRadius: "6px",
              backdropFilter: "blur(10px)",
              fontSize: "0.75rem",
              color: "#4ade80",
              boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
              animation: "float 3s ease-in-out infinite",
            }}
          >
            🟢 Currently Working
            <span
              style={{
                display: "block",
                color: "#64748b",
                fontSize: "0.65rem",
                marginTop: "0.2rem",
              }}
            >
              Full-Stack Developer
            </span>
          </div>

          {/* Floating badge 2 */}
          <div
            style={{
              position: "absolute",
              top: "20px",
              left: "-40px",
              background: "#111128",
              border: "1px solid rgba(124,58,237,0.3)",
              padding: "0.6rem 1rem",
              borderRadius: "6px",
              fontSize: "0.68rem",
              color: "#06b6d4",
              boxShadow: "0 10px 30px rgba(0,0,0,0.4)",
              animation: "float 3.5s 1s ease-in-out infinite",
            }}
          >
            ⭐ 9.05 CGPA
          </div>
        </div>
      </div>
    </section>
  );
}

// src/app/components/hero/hero.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './hero.component.html',
  styleUrls: ['./hero.component.css']
})
export class HeroComponent implements OnInit, OnDestroy {
  typedText = '';
  yearsExp = '';

  private roles = ['Full-Stack Developer', '.NET Core Expert', 'Angular Developer', 'Cloud & AWS Builder', 'API Architect'];
  private ri = 0;
  private ci = 0;
  private deleting = false;
  private timeoutId: ReturnType<typeof setTimeout> | null = null;

  ngOnInit() {
    this.yearsExp = this.calcExperience();
    this.timeoutId = setTimeout(() => this.type(), 800);
  }

  ngOnDestroy() {
    if (this.timeoutId) clearTimeout(this.timeoutId);
  }

  private calcExperience(): string {
    // Started Jan 2023 at Shaligram Infotech
    const start = new Date(2023, 0, 1);
    const now = new Date();
    const totalMonths = (now.getFullYear() - start.getFullYear()) * 12 + (now.getMonth() - start.getMonth());
    const years = Math.floor(totalMonths / 12);
    const months = totalMonths % 12;
    if (months === 0) return `${years}`;
    return `${years}.${months < 3 ? '1' : months < 6 ? '3' : months < 9 ? '5' : '8'}`;
  }

  private type() {
    const word = this.roles[this.ri];
    if (!this.deleting) {
      this.ci++;
      this.typedText = word.slice(0, this.ci);
      if (this.ci === word.length) {
        this.deleting = true;
        this.timeoutId = setTimeout(() => this.type(), 1800);
        return;
      }
    } else {
      this.ci--;
      this.typedText = word.slice(0, this.ci);
      if (this.ci === 0) {
        this.deleting = false;
        this.ri = (this.ri + 1) % this.roles.length;
        this.timeoutId = setTimeout(() => this.type(), 400);
        return;
      }
    }
    this.timeoutId = setTimeout(() => this.type(), this.deleting ? 55 : 90);
  }
}

<section id="hero" class="hero">
  <div class="hero-bg"></div>

  <div class="hero-content">
    <div class="hero-tag">
      <span class="pulse-dot"></span>
      Open to new opportunities
    </div>

    <h1>
      Hi, I'm Manav
      <span class="gradient-text">
        {{ typedText }}<span class="typing-cursor"></span>
      </span>
    </h1>

    <p class="hero-subtitle">
      Full-Stack Developer with {{ yearsExp }}+ years of experience building scalable web
      applications with Angular, .NET Core, Web API, and SQL — with growing
      expertise in React.js, Python, and AWS cloud infrastructure.
    </p>

    <div class="hero-ctas">
      <a href="#projects" class="btn-primary">View My Work</a>
      <a href="mailto:manavnanda2404@gmail.com" class="btn-outline">Get In Touch</a>
      <a href="assets/resume/Manav-Resume.pdf" download="Manav_Nanda_Resume.pdf" class="btn-outline btn-resume">
        <i class="fa-solid fa-download"></i> Resume
      </a>

    </div>

    <div class="hero-stats">
      <div class="stat-item">
        <div class="stat-num">{{ yearsExp }}+</div>
        <div class="stat-label">Yrs Experience</div>
      </div>
      <div class="stat-item">
        <div class="stat-num">10+</div>
        <div class="stat-label">Live Projects</div>
      </div>
      <div class="stat-item">
        <div class="stat-num">9.05</div>
        <div class="stat-label">B.Tech CGPA</div>
      </div>
    </div>
  </div>

  <div class="hero-photo">
    <div class="photo-frame">
      <div class="photo-img-wrap">
        <img src="images/manav.jpg" alt="Manav Nanda" class="hero-img" />
      </div>
      <div class="floating-badge">
        🟢 Currently Working
        <span>Full-Stack Developer</span>
      </div>
      <div class="floating-badge-2">🚀 10+ Live Projects</div>
    </div>
  </div>
</section>
